### ISSUE TITLE
Latest app can't download a file anymore

### ISSUE THREAD

**Issue by shazada** [Alfresco/activiti-android-app#17]
Opening a file always results in no viewer is installed (though there is one).
And downloading a file causes to crash the application.

Tested on a Lenovo Tab with 4.4.2 and Activiti version 1.1.58.

**Comment by jmpascal** [comment]
Hello,

Can you provide activiti server version number please ?

Thanks in advance.

**Comment by shazada** [comment]
Hi,

I don't know it's the alfresco activiti cloud.

**Comment by agologan** [comment]
Closed due to inactivity
