### ISSUE TITLE
how to determine the properties value for NEXUS_USERNAME and NEXUS_PASSWORD 

### ISSUE THREAD

**Issue by codeqq** [Alfresco/activiti-android-app#2]
when I try to compile activiti-android-app 1.0 in Android Studio (v1.2), it gets an error:

Error:(131, 0) Could not find property 'NEXUS_USERNAME' on Credentials [username: null].

which refers to line 131 of activiti-app\build.gradle:
128                maven {
129                    url "https://artifacts.alfresco.com/nexus/content/repositories/internal-releases/"
130                    credentials {
131                        username NEXUS_USERNAME
132                        password NEXUS_PASSWORD
133                    }
134                }

so, the question is, how to determine the properties value for NEXUS_USERNAME and NEXUS_PASSWORD ?

**Comment by jmpascal** [comment]
Fixed in 1.1 codebase.
