### ISSUE TITLE
Japanese Translation.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/activiti-android-app#98]
Hi.

Do you plan to translate Alfresco Process Services mobile applications into Japanese?

Or will it be reflected if I provide a Japanese translation based on [Alfresco/alfresco-ui-strings](https://github.com/Alfresco/alfresco-ui-strings)?

**Comment by emanuellupu** [comment]
Hi @silverskyvicto, it's not planned for addition but we are accepting contributions to the product and encourage them of course. Feel free to open a PR with the translations and once it's validated by our localization team it's going to be pushed out with the next update of APS. Thanks for raising this!
